package image

import (
	"encoding/json"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/dimipaun/fugaro/internal/config"
	"github.com/dimipaun/fugaro/internal/testutil"
)

const wantFull = `# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
# Derived image for workflow web, generated by fugaro 1.2.3
# from images/derived/Dockerfile.tmpl (design §7.2). Do not edit it: change
# the workflow's image: settings instead, or save this output as
# .fugaro/web.Dockerfile, point dockerfile: at it and edit that.
#
# Build arguments:
#   FUGARO_BASE  the Fugaro base image; Cloud Build pins it by digest
#   REPO_URL     what to clone: a git URL, or /src/repo.bundle from the build context
#   REPO_ORIGIN  the https origin URL the checkout keeps; defaults to REPO_URL
#   BASE_BRANCH  the branch to bake in
# Build secrets, all optional: git-credentials (a git credential-store file
# for REPO_URL) and one per workflow secret, mounted as a file and exported
# as that variable inside the warm-up and setup commands only.
ARG FUGARO_BASE
FROM ${FUGARO_BASE}
# The base as built FROM (Cloud Build passes its digest); cache keys use it.
ARG FUGARO_BASE
ENV FUGARO_BASE_IMAGE=${FUGARO_BASE}
ARG REPO_URL
ARG REPO_ORIGIN=${REPO_URL}
ARG BASE_BRANCH

USER root
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libvips-dev fonts-liberation \
 && rm -rf /var/lib/apt/lists/*
RUN /usr/local/lib/fugaro/install-node 24.19.0
USER fugaro

WORKDIR /work/repo
RUN --mount=type=bind,target=/src \
    --mount=type=secret,id=git-credentials,uid=1000,required=false \
    GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
      -c credential.helper='store --file=/run/secrets/git-credentials' \
      clone --quiet --branch "$BASE_BRANCH" --single-branch -- "$REPO_URL" /work/repo \
 && git remote set-url origin -- "$REPO_ORIGIN"

# Dependency warm-up for yarn.lock.
RUN --mount=type=secret,id=NPM_TOKEN,uid=1000,mode=0400,required=false if test -e /run/secrets/NPM_TOKEN; then NPM_TOKEN="$(cat /run/secrets/NPM_TOKEN)" || exit 1; export NPM_TOKEN; fi; yarn install --immutable

# Setup steps run as fugaro but may use sudo, for example for
# playwright install --with-deps. The rule is removed below.
USER root
RUN echo 'fugaro ALL=(root) NOPASSWD: ALL' > /etc/sudoers.d/fugaro-build \
 && chmod 0440 /etc/sudoers.d/fugaro-build
USER fugaro

# image.setup steps.
RUN --mount=type=secret,id=NPM_TOKEN,uid=1000,mode=0400,required=false if test -e /run/secrets/NPM_TOKEN; then NPM_TOKEN="$(cat /run/secrets/NPM_TOKEN)" || exit 1; export NPM_TOKEN; fi; npx playwright install --with-deps chromium
RUN --mount=type=secret,id=NPM_TOKEN,uid=1000,mode=0400,required=false if test -e /run/secrets/NPM_TOKEN; then NPM_TOKEN="$(cat /run/secrets/NPM_TOKEN)" || exit 1; export NPM_TOKEN; fi; mkdir -p build

USER root
RUN rm -f /etc/sudoers.d/fugaro-build \
 && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \
 && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }
USER fugaro

RUN /usr/local/lib/fugaro/finalize-checkout /work/repo

# The build time, which Cloud Build passes (empty in a local build). It is
# declared here, so a new value never invalidates the cached steps above.
ARG FUGARO_BUILT_AT=""
# What the image was built from, for the runner to report how old the image
# was at launch. built_at is left out of a local build. The checkout belongs
# to fugaro, so root is told to trust it.
USER root
RUN mkdir -p /etc/fugaro \
 && commit="$(git -c safe.directory=/work/repo -C /work/repo rev-parse HEAD)" \
 && { printf '{'; [ -z "$FUGARO_BUILT_AT" ] || printf '"built_at":"%s",' "$FUGARO_BUILT_AT"; printf '"commit":"%s"}\n' "$commit"; } > /etc/fugaro/image.json \
 && chmod 0644 /etc/fugaro/image.json
USER fugaro
`

const wantMinimal = `# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
# Derived image for workflow app, generated by fugaro dev
# from images/derived/Dockerfile.tmpl (design §7.2). Do not edit it: change
# the workflow's image: settings instead, or save this output as
# .fugaro/app.Dockerfile, point dockerfile: at it and edit that.
#
# Build arguments:
#   FUGARO_BASE  the Fugaro base image; Cloud Build pins it by digest
#   REPO_URL     what to clone: a git URL, or /src/repo.bundle from the build context
#   REPO_ORIGIN  the https origin URL the checkout keeps; defaults to REPO_URL
#   BASE_BRANCH  the branch to bake in
# Build secrets, all optional: git-credentials (a git credential-store file
# for REPO_URL) and one per workflow secret, mounted as a file and exported
# as that variable inside the warm-up and setup commands only.
ARG FUGARO_BASE
FROM ${FUGARO_BASE}
# The base as built FROM (Cloud Build passes its digest); cache keys use it.
ARG FUGARO_BASE
ENV FUGARO_BASE_IMAGE=${FUGARO_BASE}
ARG REPO_URL
ARG REPO_ORIGIN=${REPO_URL}
ARG BASE_BRANCH

WORKDIR /work/repo
RUN --mount=type=bind,target=/src \
    --mount=type=secret,id=git-credentials,uid=1000,required=false \
    GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
      -c credential.helper='store --file=/run/secrets/git-credentials' \
      clone --quiet --branch "$BASE_BRANCH" --single-branch -- "$REPO_URL" /work/repo \
 && git remote set-url origin -- "$REPO_ORIGIN"

USER root
RUN rm -f /etc/sudoers.d/fugaro-build \
 && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \
 && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }
USER fugaro

RUN /usr/local/lib/fugaro/finalize-checkout /work/repo

# The build time, which Cloud Build passes (empty in a local build). It is
# declared here, so a new value never invalidates the cached steps above.
ARG FUGARO_BUILT_AT=""
# What the image was built from, for the runner to report how old the image
# was at launch. built_at is left out of a local build. The checkout belongs
# to fugaro, so root is told to trust it.
USER root
RUN mkdir -p /etc/fugaro \
 && commit="$(git -c safe.directory=/work/repo -C /work/repo rev-parse HEAD)" \
 && { printf '{'; [ -z "$FUGARO_BUILT_AT" ] || printf '"built_at":"%s",' "$FUGARO_BUILT_AT"; printf '"commit":"%s"}\n' "$commit"; } > /etc/fugaro/image.json \
 && chmod 0644 /etc/fugaro/image.json
USER fugaro
`

func TestRenderFull(t *testing.T) {
	got, err := Render(RenderInput{
		Workflow: "web", Base: "web-node", Version: "1.2.3",
		Image: config.Image{
			Node:  "24.19.0",
			Apt:   []string{"libvips-dev", "fonts-liberation"},
			Setup: []string{"npx playwright install --with-deps chromium", "mkdir -p build"},
		},
		PM:      &config.NodePM{Name: "yarn", Berry: true, Lockfile: "yarn.lock", Install: "yarn install --immutable"},
		Secrets: []string{"NPM_TOKEN"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantFull {
		t.Errorf("Render =\n%s\nwant\n%s", got, wantFull)
	}
	if msgs := config.LintDockerfile(got, "web-node"); len(msgs) > 0 {
		t.Errorf("the rendered Dockerfile breaks the repository-Dockerfile contract: %v", msgs)
	}
	// Once image.setup steps run as fugaro with
	// build-time sudo, the derived image must remove both the sudo grant
	// and sudo's setuid bit, leaving no privilege-escalation path.
	if !strings.Contains(string(got), "RUN rm -f /etc/sudoers.d/fugaro-build \\\n && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \\\n && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }\n") {
		t.Errorf("Render does not remove the sudo grant and drop sudo's setuid bit:\n%s", got)
	}
	// The sudo grant must be active only
	// around the setup steps, not during the dependency warm-up, so it
	// must be written after "Dependency warm-up" and before "image.setup
	// steps.".
	grantIdx := strings.Index(string(got), "fugaro ALL=(root) NOPASSWD: ALL")
	warmUpIdx := strings.Index(string(got), "# Dependency warm-up")
	setupIdx := strings.Index(string(got), "# image.setup steps.")
	if grantIdx < 0 || warmUpIdx < 0 || setupIdx < 0 || !(warmUpIdx < grantIdx && grantIdx < setupIdx) {
		t.Errorf("the passwordless-sudo grant must be written after the warm-up and before the image.setup steps, not before it:\n%s", got)
	}
}

// A setup step starting with "-" or "["
// would be read as a RUN flag (a build-time secret mount, for example) or
// exec form rather than a shell command, which could smuggle the clone
// credential into a layer. internal/config already rejects this at
// fugaro.yaml validation time, but Render is exported and doesn't
// re-validate, so it must refuse such steps too.
func TestRenderRefusesFlagLikeSetupStep(t *testing.T) {
	cases := []string{
		"--mount=type=secret,id=git-credentials,target=/tmp/c cp /tmp/c /work/repo/.leak",
		`["sh", "-c", "cp /run/secrets/git-credentials /work/repo/.leak"]`,
		"  --also-leading-whitespace",
	}
	for _, step := range cases {
		if _, err := Render(RenderInput{Workflow: "web", Base: "web-node", Image: config.Image{Setup: []string{step}}}); err == nil {
			t.Errorf("Render(%q) = nil error, want a refusal", step)
		}
	}
}

// Cloud Build's docker daemon refuses env= secret mounts ("requested
// experimental feature exec.secretenv is not supported by build server"),
// so every secret mount in a rendered Dockerfile must be a file mount.
func TestRenderSecretMountsAreFiles(t *testing.T) {
	got, err := Render(RenderInput{
		Workflow: "web", Base: "web-node",
		Image:   config.Image{Setup: []string{"true"}},
		PM:      &config.NodePM{Lockfile: "package-lock.json", Install: "npm ci"},
		Secrets: []string{"NPM_TOKEN", "OTHER_TOKEN"},
	})
	if err != nil {
		t.Fatal(err)
	}
	mounts := regexp.MustCompile(`--mount=type=secret,\S*`).FindAllString(string(got), -1)
	if len(mounts) != 5 { // git-credentials, then both secrets on the warm-up and the setup step
		t.Fatalf("secret mounts = %q", mounts)
	}
	for _, m := range mounts {
		if strings.Contains(m, "env=") {
			t.Errorf("secret mount %q uses env=, which Cloud Build's daemon refuses", m)
		}
	}
}

// The prefix Render puts before a warm-up or setup command exports each
// mounted secret, leaves a missing one unset, and keeps the value off the
// command line. It runs here under sh with /run/secrets pointed at a
// temporary directory.
func TestRenderSecretPrefixExports(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh")
	}
	got, err := Render(RenderInput{
		Workflow: "web", Base: "web-node",
		Image:   config.Image{Setup: []string{`printf '%s|%s|%s' "$A_TOKEN" "${B_TOKEN-unset}" "$C_TOKEN" && env | grep -c _TOKEN= >&2`}},
		Secrets: []string{"A_TOKEN", "B_TOKEN", "C_TOKEN"},
	})
	if err != nil {
		t.Fatal(err)
	}
	var line string
	for _, l := range strings.Split(string(got), "\n") {
		if strings.Contains(l, "printf") && strings.Contains(l, "--mount=type=secret") {
			line = l
		}
	}
	_, cmd, ok := strings.Cut(line, ",required=false if ")
	if !ok || strings.Count(line, "--mount=type=secret,") != 3 {
		t.Fatalf("setup line = %q", line)
	}
	dir := t.TempDir()
	testutil.WriteFiles(t, dir, map[string]string{"A_TOKEN": "a value; $(x) 'q\"\n", "C_TOKEN": "c"})
	c := exec.Command(sh, "-c", strings.ReplaceAll("if "+cmd, "/run/secrets/", dir+"/"))
	c.Env = []string{"PATH=" + os.Getenv("PATH")}
	var stderr strings.Builder
	c.Stderr = &stderr
	out, err := c.Output()
	if err != nil {
		t.Fatalf("%v\n%s", err, stderr.String())
	}
	if want := `a value; $(x) 'q"|unset|c`; string(out) != want {
		t.Errorf("the command saw %q, want %q", out, want)
	}
	if strings.TrimSpace(stderr.String()) != "2" {
		t.Errorf("exported secret variables = %s, want 2 (B_TOKEN unset)", stderr.String())
	}
	if strings.Contains(line, "a value") {
		t.Error("the secret value is on the RUN line")
	}
}

func TestRenderMinimal(t *testing.T) {
	got, err := Render(RenderInput{Workflow: "app", Base: "web-node", Version: "dev"})
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantMinimal {
		t.Errorf("Render =\n%s\nwant\n%s", got, wantMinimal)
	}
	if msgs := config.LintDockerfile(got, "web-node"); len(msgs) > 0 {
		t.Errorf("the rendered Dockerfile breaks the repository-Dockerfile contract: %v", msgs)
	}
}

// warmUpBlock is the warm-up section of a derived Dockerfile rendered with
// the NPM_TOKEN secret: the comment and the RUN line.
func warmUpBlock(comment, lockfile, install string) string {
	return "\n# Dependency warm-up for " + lockfile + "." + comment + "\n" +
		`RUN --mount=type=secret,id=NPM_TOKEN,uid=1000,mode=0400,required=false if test -e /run/secrets/NPM_TOKEN; then NPM_TOKEN="$(cat /run/secrets/NPM_TOKEN)" || exit 1; export NPM_TOKEN; fi; ` + install + "\n"
}

const skipComment = "\n# image.skip_build_scripts: package build scripts do not run here, so\n# the workflow's build command builds what the repository needs."

// renderPMs are the package managers the warm-up renders for, with their
// plain install and the one that skips build scripts.
var renderPMs = []struct {
	pm          config.NodePM
	plain, skip string
}{
	{config.NodePM{Name: "yarn", Berry: true, Lockfile: "yarn.lock", Install: "yarn install --immutable"},
		"yarn install --immutable", "yarn install --immutable --mode=skip-build"},
	{config.NodePM{Name: "yarn", Lockfile: "yarn.lock", Install: "yarn install --frozen-lockfile"},
		"yarn install --frozen-lockfile", "yarn install --frozen-lockfile --ignore-scripts"},
	{config.NodePM{Name: "npm", Lockfile: "package-lock.json", Install: "npm ci"},
		"npm ci", "npm ci --ignore-scripts"},
	{config.NodePM{Name: "pnpm", Lockfile: "pnpm-lock.yaml", Install: "pnpm fetch && pnpm install --offline --frozen-lockfile"},
		"pnpm fetch && pnpm install --offline --frozen-lockfile", "pnpm fetch && pnpm install --offline --frozen-lockfile --ignore-scripts"},
}

// fullInput is TestRenderFull's input with pm as the package manager.
func fullInput(pm config.NodePM, skip bool) RenderInput {
	return RenderInput{
		Workflow: "web", Base: "web-node", Version: "1.2.3",
		Image: config.Image{
			Node:             "24.19.0",
			Apt:              []string{"libvips-dev", "fonts-liberation"},
			Setup:            []string{"npx playwright install --with-deps chromium", "mkdir -p build"},
			SkipBuildScripts: skip,
		},
		PM:      &pm,
		Secrets: []string{"NPM_TOKEN"},
	}
}

// With image.skip_build_scripts, each package manager's warm-up installs
// without lifecycle or build scripts, and the rest of the Dockerfile is
// TestRenderFull's, byte for byte.
func TestRenderSkipBuildScripts(t *testing.T) {
	yarnBlock := warmUpBlock("", "yarn.lock", "yarn install --immutable")
	if !strings.Contains(wantFull, yarnBlock) {
		t.Fatalf("wantFull lacks %q", yarnBlock)
	}
	for _, tc := range renderPMs {
		t.Run(tc.pm.Lockfile+" "+tc.plain, func(t *testing.T) {
			got, err := Render(fullInput(tc.pm, true))
			if err != nil {
				t.Fatal(err)
			}
			want := strings.Replace(wantFull, yarnBlock, warmUpBlock(skipComment, tc.pm.Lockfile, tc.skip), 1)
			if string(got) != want {
				t.Errorf("Render =\n%s\nwant\n%s", got, want)
			}
			if msgs := config.LintDockerfile(got, "web-node"); len(msgs) > 0 {
				t.Errorf("the rendered Dockerfile breaks the repository-Dockerfile contract: %v", msgs)
			}
		})
	}
}

// Leaving image.skip_build_scripts off renders exactly what fugaro rendered
// before the setting existed, for every package manager.
func TestRenderDefaultWarmUpUnchanged(t *testing.T) {
	for _, tc := range renderPMs {
		t.Run(tc.pm.Lockfile+" "+tc.plain, func(t *testing.T) {
			got, err := Render(fullInput(tc.pm, false))
			if err != nil {
				t.Fatal(err)
			}
			want := strings.Replace(wantFull, warmUpBlock("", "yarn.lock", "yarn install --immutable"), warmUpBlock("", tc.pm.Lockfile, tc.plain), 1)
			if string(got) != want {
				t.Errorf("Render =\n%s\nwant\n%s", got, want)
			}
		})
	}
}

func TestDockerfileSkipBuildScripts(t *testing.T) {
	root := t.TempDir()
	testutil.WriteFiles(t, root, map[string]string{"package.json": `{"packageManager":"yarn@4.16.0"}`, "yarn.lock": ""})
	cfg := parseConfig(t, strings.Replace(renderYAML, "    base: web-node\n", "    base: web-node\n    image: { skip_build_scripts: true }\n", 1))
	data, _, err := Dockerfile(root, cfg, "web", "dev")
	if err != nil {
		t.Fatal(err)
	}
	if want := warmUpBlock(skipComment, "yarn.lock", "yarn install --immutable --mode=skip-build"); !strings.Contains(string(data), want) {
		t.Fatalf("Dockerfile lacks %q:\n%s", want, data)
	}
}

func TestRenderRefusesUnpublishedBase(t *testing.T) {
	if _, err := Render(RenderInput{Workflow: "server", Base: "server-jvm"}); err == nil || !strings.Contains(err.Error(), "server-jvm has no published image yet") {
		t.Fatalf("err = %v", err)
	}
}

func parseConfig(t *testing.T, yaml string) *config.Config {
	t.Helper()
	cfg, problems := config.Parse([]byte(yaml))
	if len(problems) > 0 {
		t.Fatal(problems)
	}
	return cfg
}

const renderYAML = `version: 1
git: { provider: github }
workflows:
  web:
    base: web-node
    commands: { build: npm run build, test: npm test }
    secrets:
      - { name: npm-token, env: NPM_TOKEN }
`

func TestDockerfileDetectsPackageManager(t *testing.T) {
	root := t.TempDir()
	testutil.WriteFiles(t, root, map[string]string{"package.json": `{"name":"app"}`, "package-lock.json": "{}"})
	data, repoFile, err := Dockerfile(root, parseConfig(t, renderYAML), "web", "dev")
	if err != nil || repoFile != "" {
		t.Fatalf("repoFile %q, err %v", repoFile, err)
	}
	if want := "# Dependency warm-up for package-lock.json.\n" + `RUN --mount=type=secret,id=NPM_TOKEN,uid=1000,mode=0400,required=false if test -e /run/secrets/NPM_TOKEN; then NPM_TOKEN="$(cat /run/secrets/NPM_TOKEN)" || exit 1; export NPM_TOKEN; fi; npm ci` + "\n"; !strings.Contains(string(data), want) {
		t.Fatalf("Dockerfile lacks %q:\n%s", want, data)
	}
}

func TestDockerfileUsesRepositoryFile(t *testing.T) {
	root := t.TempDir()
	const df = "ARG FUGARO_BASE\nFROM ${FUGARO_BASE}\nRUN git clone \"$REPO_URL\" /work/repo\n"
	testutil.WriteFiles(t, root, map[string]string{".fugaro/web.Dockerfile": df})
	cfg := parseConfig(t, strings.Replace(renderYAML, "    base: web-node\n", "    base: web-node\n    dockerfile: .fugaro/web.Dockerfile\n", 1))
	data, repoFile, err := Dockerfile(root, cfg, "web", "dev")
	if err != nil || repoFile != ".fugaro/web.Dockerfile" || string(data) != df {
		t.Fatalf("data %q, repoFile %q, err %v", data, repoFile, err)
	}
}

func TestDockerfileUnknownWorkflow(t *testing.T) {
	if _, _, err := Dockerfile(t.TempDir(), parseConfig(t, renderYAML), "api", "dev"); err == nil || !strings.Contains(err.Error(), `no workflow "api"`) {
		t.Fatalf("err = %v", err)
	}
}

// The template's last step records what the image was built from, at the
// path the runner reads. The step is run here, against a scratch checkout,
// with and without the build time Cloud Build passes.
func TestTemplateWritesImageJSON(t *testing.T) {
	rendered, err := Render(RenderInput{Workflow: "app", Base: "web-node", Version: "dev"})
	if err != nil {
		t.Fatal(err)
	}
	out := string(rendered)
	if strings.Index(out, "finalize-checkout") > strings.Index(out, "/etc/fugaro/image.json") || !strings.HasSuffix(out, "USER fugaro\n") {
		t.Fatalf("image.json is not written after the checkout is finalized, as fugaro:\n%s", out)
	}
	var step []string
	for _, line := range strings.Split(out, "\n") {
		switch {
		case strings.HasPrefix(line, "RUN mkdir -p /etc/fugaro"):
			step = append(step, strings.TrimSuffix(strings.TrimPrefix(line, "RUN "), "\\"))
		case len(step) > 0 && strings.HasPrefix(line, " && "):
			step = append(step, strings.TrimSuffix(line, "\\"))
		}
	}
	if len(step) != 4 {
		t.Fatalf("the image.json step = %q", step)
	}

	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh")
	}
	testutil.IsolateGit(t)
	repo := t.TempDir()
	testutil.Git(t, repo, "init", "--quiet", "-b", "main", repo)
	testutil.WriteFiles(t, repo, map[string]string{"a.txt": "a\n"})
	testutil.Git(t, repo, "add", "-A")
	testutil.Git(t, repo, "commit", "--quiet", "-m", "one")
	head := testutil.Git(t, repo, "rev-parse", "HEAD")

	for _, builtAt := range []string{"2026-09-28T10:00:00Z", ""} {
		etc := filepath.Join(t.TempDir(), "etc", "fugaro")
		script := strings.NewReplacer("/etc/fugaro", etc, "/work/repo", repo).Replace(strings.Join(step, " "))
		cmd := exec.Command(sh, "-c", script)
		cmd.Env = append(os.Environ(), "FUGARO_BUILT_AT="+builtAt)
		if b, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("%v\n%s", err, b)
		}
		data, err := os.ReadFile(filepath.Join(etc, "image.json"))
		if err != nil {
			t.Fatal(err)
		}
		var got map[string]string
		if err := json.Unmarshal(data, &got); err != nil {
			t.Fatalf("image.json is not JSON: %v\n%s", err, data)
		}
		want := map[string]string{"commit": head}
		if builtAt != "" {
			want["built_at"] = builtAt
		}
		if !maps.Equal(got, want) {
			t.Fatalf("image.json with FUGARO_BUILT_AT=%q = %v, want %v", builtAt, got, want)
		}
	}
}
