package image

import (
	"strings"
	"testing"

	"github.com/dimipaun/fugaro/internal/config"
	"github.com/dimipaun/fugaro/internal/testutil"
)

const wantFull = `# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
# Derived image for workflow web, generated by fugaro 1.2.3
# from images/derived/Dockerfile.tmpl (design §7.2). Do not edit it: change
# the workflow's image: settings instead, or save this output as
# .fugaro/web.Dockerfile, point dockerfile: at it and edit that.
#
# Build arguments:
#   FUGARO_BASE  the Fugaro base image; Cloud Build pins it by digest
#   REPO_URL     what to clone: a git URL, or /src/repo.bundle from the build context
#   REPO_ORIGIN  the https origin URL the checkout keeps; defaults to REPO_URL
#   BASE_BRANCH  the branch to bake in
# Build secrets, all optional: git-credentials (a git credential-store file
# for REPO_URL) and one per workflow secret, exposed as that variable.
ARG FUGARO_BASE
FROM ${FUGARO_BASE}
# The base as built FROM (Cloud Build passes its digest); cache keys use it.
ARG FUGARO_BASE
ENV FUGARO_BASE_IMAGE=${FUGARO_BASE}
ARG REPO_URL
ARG REPO_ORIGIN=${REPO_URL}
ARG BASE_BRANCH

USER root
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libvips-dev fonts-liberation \
 && rm -rf /var/lib/apt/lists/*
RUN /usr/local/lib/fugaro/install-node 24.19.0
USER fugaro

WORKDIR /work/repo
RUN --mount=type=bind,target=/src \
    --mount=type=secret,id=git-credentials,uid=1000,required=false \
    GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
      -c credential.helper='store --file=/run/secrets/git-credentials' \
      clone --quiet --branch "$BASE_BRANCH" --single-branch -- "$REPO_URL" /work/repo \
 && git remote set-url origin -- "$REPO_ORIGIN"

# Dependency warm-up for yarn.lock.
RUN --mount=type=secret,id=NPM_TOKEN,env=NPM_TOKEN,required=false yarn install --immutable

# Setup steps run as fugaro but may use sudo, for example for
# playwright install --with-deps. The rule is removed below.
USER root
RUN echo 'fugaro ALL=(root) NOPASSWD: ALL' > /etc/sudoers.d/fugaro-build \
 && chmod 0440 /etc/sudoers.d/fugaro-build
USER fugaro

# image.setup steps.
RUN --mount=type=secret,id=NPM_TOKEN,env=NPM_TOKEN,required=false npx playwright install --with-deps chromium
RUN --mount=type=secret,id=NPM_TOKEN,env=NPM_TOKEN,required=false mkdir -p build

USER root
RUN rm -f /etc/sudoers.d/fugaro-build \
 && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \
 && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }
USER fugaro

RUN /usr/local/lib/fugaro/finalize-checkout /work/repo
`

const wantMinimal = `# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
# Derived image for workflow app, generated by fugaro dev
# from images/derived/Dockerfile.tmpl (design §7.2). Do not edit it: change
# the workflow's image: settings instead, or save this output as
# .fugaro/app.Dockerfile, point dockerfile: at it and edit that.
#
# Build arguments:
#   FUGARO_BASE  the Fugaro base image; Cloud Build pins it by digest
#   REPO_URL     what to clone: a git URL, or /src/repo.bundle from the build context
#   REPO_ORIGIN  the https origin URL the checkout keeps; defaults to REPO_URL
#   BASE_BRANCH  the branch to bake in
# Build secrets, all optional: git-credentials (a git credential-store file
# for REPO_URL) and one per workflow secret, exposed as that variable.
ARG FUGARO_BASE
FROM ${FUGARO_BASE}
# The base as built FROM (Cloud Build passes its digest); cache keys use it.
ARG FUGARO_BASE
ENV FUGARO_BASE_IMAGE=${FUGARO_BASE}
ARG REPO_URL
ARG REPO_ORIGIN=${REPO_URL}
ARG BASE_BRANCH

WORKDIR /work/repo
RUN --mount=type=bind,target=/src \
    --mount=type=secret,id=git-credentials,uid=1000,required=false \
    GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
      -c credential.helper='store --file=/run/secrets/git-credentials' \
      clone --quiet --branch "$BASE_BRANCH" --single-branch -- "$REPO_URL" /work/repo \
 && git remote set-url origin -- "$REPO_ORIGIN"

USER root
RUN rm -f /etc/sudoers.d/fugaro-build \
 && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \
 && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }
USER fugaro

RUN /usr/local/lib/fugaro/finalize-checkout /work/repo
`

func TestRenderFull(t *testing.T) {
	got, err := Render(RenderInput{
		Workflow: "web", Base: "web-node", Version: "1.2.3",
		Image: config.Image{
			Node:  "24.19.0",
			Apt:   []string{"libvips-dev", "fonts-liberation"},
			Setup: []string{"npx playwright install --with-deps chromium", "mkdir -p build"},
		},
		PM:      &config.NodePM{Name: "yarn", Berry: true, Lockfile: "yarn.lock", Install: "yarn install --immutable"},
		Secrets: []string{"NPM_TOKEN"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantFull {
		t.Errorf("Render =\n%s\nwant\n%s", got, wantFull)
	}
	if msgs := config.LintDockerfile(got, "web-node"); len(msgs) > 0 {
		t.Errorf("the rendered Dockerfile breaks the repository-Dockerfile contract: %v", msgs)
	}
	// Controller ruling: once image.setup steps run as fugaro with
	// build-time sudo, the derived image must remove both the sudo grant
	// and sudo's setuid bit, leaving no privilege-escalation path.
	if !strings.Contains(string(got), "RUN rm -f /etc/sudoers.d/fugaro-build \\\n && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \\\n && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }\n") {
		t.Errorf("Render does not remove the sudo grant and drop sudo's setuid bit:\n%s", got)
	}
	// Fix round 1 (security review): the sudo grant must be active only
	// around the setup steps, not during the dependency warm-up, so it
	// must be written after "Dependency warm-up" and before "image.setup
	// steps.".
	grantIdx := strings.Index(string(got), "fugaro ALL=(root) NOPASSWD: ALL")
	warmUpIdx := strings.Index(string(got), "# Dependency warm-up")
	setupIdx := strings.Index(string(got), "# image.setup steps.")
	if grantIdx < 0 || warmUpIdx < 0 || setupIdx < 0 || !(warmUpIdx < grantIdx && grantIdx < setupIdx) {
		t.Errorf("the passwordless-sudo grant must be written after the warm-up and before the image.setup steps, not before it:\n%s", got)
	}
}

// Fix round 1 (security review): a setup step starting with "-" or "["
// would be read as a RUN flag (a build-time secret mount, for example) or
// exec form rather than a shell command, which could smuggle the clone
// credential into a layer. internal/config already rejects this at
// fugaro.yaml validation time, but Render is exported and doesn't
// re-validate, so it must refuse such steps too.
func TestRenderRefusesFlagLikeSetupStep(t *testing.T) {
	cases := []string{
		"--mount=type=secret,id=git-credentials,target=/tmp/c cp /tmp/c /work/repo/.leak",
		`["sh", "-c", "cp /run/secrets/git-credentials /work/repo/.leak"]`,
		"  --also-leading-whitespace",
	}
	for _, step := range cases {
		if _, err := Render(RenderInput{Workflow: "web", Base: "web-node", Image: config.Image{Setup: []string{step}}}); err == nil {
			t.Errorf("Render(%q) = nil error, want a refusal", step)
		}
	}
}

func TestRenderMinimal(t *testing.T) {
	got, err := Render(RenderInput{Workflow: "app", Base: "web-node", Version: "dev"})
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantMinimal {
		t.Errorf("Render =\n%s\nwant\n%s", got, wantMinimal)
	}
	if msgs := config.LintDockerfile(got, "web-node"); len(msgs) > 0 {
		t.Errorf("the rendered Dockerfile breaks the repository-Dockerfile contract: %v", msgs)
	}
}

func TestRenderRefusesUnpublishedBase(t *testing.T) {
	if _, err := Render(RenderInput{Workflow: "server", Base: "server-jvm"}); err == nil || !strings.Contains(err.Error(), "server-jvm has no published image yet") {
		t.Fatalf("err = %v", err)
	}
}

func parseConfig(t *testing.T, yaml string) *config.Config {
	t.Helper()
	cfg, problems := config.Parse([]byte(yaml))
	if len(problems) > 0 {
		t.Fatal(problems)
	}
	return cfg
}

const renderYAML = `version: 1
git: { provider: github }
workflows:
  web:
    base: web-node
    commands: { build: npm run build, test: npm test }
    secrets:
      - { name: npm-token, env: NPM_TOKEN }
`

func TestDockerfileDetectsPackageManager(t *testing.T) {
	root := t.TempDir()
	testutil.WriteFiles(t, root, map[string]string{"package.json": `{"name":"app"}`, "package-lock.json": "{}"})
	data, repoFile, err := Dockerfile(root, parseConfig(t, renderYAML), "web", "dev")
	if err != nil || repoFile != "" {
		t.Fatalf("repoFile %q, err %v", repoFile, err)
	}
	if want := "# Dependency warm-up for package-lock.json.\nRUN --mount=type=secret,id=NPM_TOKEN,env=NPM_TOKEN,required=false npm ci\n"; !strings.Contains(string(data), want) {
		t.Fatalf("Dockerfile lacks %q:\n%s", want, data)
	}
}

func TestDockerfileUsesRepositoryFile(t *testing.T) {
	root := t.TempDir()
	const df = "ARG FUGARO_BASE\nFROM ${FUGARO_BASE}\nRUN git clone \"$REPO_URL\" /work/repo\n"
	testutil.WriteFiles(t, root, map[string]string{".fugaro/web.Dockerfile": df})
	cfg := parseConfig(t, strings.Replace(renderYAML, "    base: web-node\n", "    base: web-node\n    dockerfile: .fugaro/web.Dockerfile\n", 1))
	data, repoFile, err := Dockerfile(root, cfg, "web", "dev")
	if err != nil || repoFile != ".fugaro/web.Dockerfile" || string(data) != df {
		t.Fatalf("data %q, repoFile %q, err %v", data, repoFile, err)
	}
}

func TestDockerfileUnknownWorkflow(t *testing.T) {
	if _, _, err := Dockerfile(t.TempDir(), parseConfig(t, renderYAML), "api", "dev"); err == nil || !strings.Contains(err.Error(), `no workflow "api"`) {
		t.Fatalf("err = %v", err)
	}
}
