package runner_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

var (
	goldenTime = regexp.MustCompile(`\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?Z`)
	goldenSHA  = regexp.MustCompile(`\b[0-9a-f]{40}\b|\b[0-9a-f]{7}\b`)
	goldenDur  = regexp.MustCompile(`\| (\d+(\.\d+)?(ms|µs|s|m\d+s|m|h\d+m\d+s)) \|`)
)

// normalize blanks what differs between two runs of the same task: clock
// readings, durations and commit hashes.
func normalize(s string) string {
	s = goldenTime.ReplaceAllString(s, "<time>")
	s = goldenSHA.ReplaceAllString(s, "<sha>")
	return goldenDur.ReplaceAllString(s, "| <dur> |")
}

func normalizeResult(t *testing.T, raw []byte) string {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	var walk func(any)
	walk = func(x any) {
		switch x := x.(type) {
		case map[string]any:
			for k, e := range x {
				if k == "duration_s" {
					x[k] = 0
				} else {
					walk(e)
				}
			}
		case []any:
			for _, e := range x {
				walk(e)
			}
		}
	}
	walk(v)
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return normalize(string(out)) + "\n"
}

// TestNoPolicyIsM9aBehaviour is the golden for a repository that sets no
// policy anywhere: no budget key, no policy env. Its result.json and
// report.md match, once normalized, what M9a (origin/main before M9a.1)
// wrote for the same hermetic run, and the record has no policy object.
// The golden files were generated by running this test on that tree with
// FUGARO_UPDATE_GOLDEN=1.
func TestNoPolicyIsM9aBehaviour(t *testing.T) {
	h := newHarness(t, "", nil)
	if _, err := h.run(t, implement("feature"), review("ship", 0)); err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	rawResult, err := h.bucket.ReadAll(ctx, h.store.Prefix()+"result.json")
	if err != nil {
		t.Fatal(err)
	}
	rawReport, err := h.bucket.ReadAll(ctx, h.store.Prefix()+"report.md")
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{
		"nopolicy_result.json": normalizeResult(t, rawResult),
		"nopolicy_report.md":   normalize(string(rawReport)),
	}
	for name, text := range got {
		path := filepath.Join("testdata", name)
		if os.Getenv("FUGARO_UPDATE_GOLDEN") != "" {
			if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if string(want) != text {
			t.Errorf("%s differs from the M9a golden:\n--- got ---\n%s\n--- want ---\n%s", name, text, want)
		}
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(rawResult, &m); err != nil {
		t.Fatal(err)
	}
	if _, ok := m["policy"]; ok {
		t.Errorf("a run with no policy wrote a policy object: %s", m["policy"])
	}
}
