package runner_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/dimipaun/fugaro/internal/runner"
	"github.com/dimipaun/fugaro/internal/testutil"
)

var (
	goldenTime = regexp.MustCompile(`\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?Z`)
	goldenSHA  = regexp.MustCompile(`\b[0-9a-f]{40}\b|\b[0-9a-f]{7}\b`)
	goldenDur  = regexp.MustCompile(`\| (\d+(\.\d+)?(ms|µs|s|m\d+s|m|h\d+m\d+s)) \|`)
)

// normalize blanks what differs between two runs of the same task: clock
// readings, durations and commit hashes.
func normalize(s string) string {
	s = goldenTime.ReplaceAllString(s, "<time>")
	s = goldenSHA.ReplaceAllString(s, "<sha>")
	return goldenDur.ReplaceAllString(s, "| <dur> |")
}

func normalizeResult(t *testing.T, raw []byte) string {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	var walk func(any)
	walk = func(x any) {
		switch x := x.(type) {
		case map[string]any:
			for k, e := range x {
				if k == "duration_s" {
					x[k] = 0
				} else {
					walk(e)
				}
			}
		case []any:
			for _, e := range x {
				walk(e)
			}
		}
	}
	walk(v)
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return normalize(string(out)) + "\n"
}

// oldFlowCfg is the fixture config with git.pr.early_draft and
// git.pr.checkpoints both false: the finalize-only pull request flow these
// goldens were recorded with, which the two keys together restore exactly.
func oldFlowCfg(t *testing.T) string {
	t.Helper()
	return oldFlow(testutil.FixtureFiles(t)["fugaro.yaml"])
}

// oldFlow turns the early draft and checkpoints off in cfg.
func oldFlow(cfg string) string {
	return strings.Replace(cfg, "  base_branch: main\n", "  base_branch: main\n  pr: { early_draft: false, checkpoints: false }\n", 1)
}

// TestNoPolicyIsM9aBehaviour is the golden for a repository that sets no
// policy anywhere: no budget key, no policy env. Its result.json and
// report.md match, once normalized, what M9a (origin/main before M9a.1)
// wrote for the same hermetic run, and the record has no policy object.
// The golden files were generated by running this test on that tree with
// FUGARO_UPDATE_GOLDEN=1.
func TestNoPolicyIsM9aBehaviour(t *testing.T) {
	h := newHarness(t, oldFlowCfg(t), nil)
	checkGolden(t, h, "nopolicy", false)
}

// TestCeilingOnlyPolicyGolden pins the record of a repository with no policy
// of its own whose project config sets a ceiling: the policy object is
// written whenever any key has a source, ceiling included, and the report is
// unchanged (nothing was ignored).
func TestCeilingOnlyPolicyGolden(t *testing.T) {
	h := newHarness(t, oldFlowCfg(t), nil)
	h.deps.Spend = ceilingOf(t, runner.MaxRunUSDEnv, "5", runner.MaxRunTokensEnv, "900000")
	checkGolden(t, h, "ceiling", true)
}

// checkGolden runs the hermetic task and compares the stored result.json and
// report.md with testdata/<name>_*; withPolicy says whether the record has a
// policy object.
func checkGolden(t *testing.T, h *harness, name string, withPolicy bool) {
	t.Helper()
	if _, err := h.run(t, implement("feature"), review("ship", 0)); err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	rawResult, err := h.bucket.ReadAll(ctx, h.store.Prefix()+"result.json")
	if err != nil {
		t.Fatal(err)
	}
	rawReport, err := h.bucket.ReadAll(ctx, h.store.Prefix()+"report.md")
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{
		name + "_result.json": normalizeResult(t, rawResult),
		name + "_report.md":   normalize(string(rawReport)),
	}
	for name, text := range got {
		path := filepath.Join("testdata", name)
		if os.Getenv("FUGARO_UPDATE_GOLDEN") != "" {
			if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if string(want) != text {
			t.Errorf("%s differs from the M9a golden:\n--- got ---\n%s\n--- want ---\n%s", name, text, want)
		}
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(rawResult, &m); err != nil {
		t.Fatal(err)
	}
	if _, ok := m["policy"]; ok != withPolicy {
		t.Errorf("policy object present = %v, want %v: %s", ok, withPolicy, m["policy"])
	}
}
