# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
# Derived image for workflow api, generated by fugaro 0.0.0
# from images/derived/Dockerfile.tmpl (design §7.2). Do not edit it: change
# the workflow's image: settings instead, or save this output as
# .fugaro/api.Dockerfile, point dockerfile: at it and edit that.
#
# Build arguments:
#   FUGARO_BASE  the Fugaro base image; Cloud Build pins it by digest
#   REPO_URL     what to clone: a git URL, or /src/repo.bundle from the build context
#   REPO_ORIGIN  the https origin URL the checkout keeps; defaults to REPO_URL
#   BASE_BRANCH  the branch to bake in
#   FUGARO_COMMIT  the commit to bake in; Cloud Build passes the one its
#                render step read, and without it the branch's head is used
# Build secrets, all optional: git-credentials (a git credential-store file
# for REPO_URL) and one per workflow secret, mounted as a file and exported
# as that variable inside the warm-up and setup commands only.
ARG FUGARO_BASE
FROM ${FUGARO_BASE}
# The base as built FROM (Cloud Build passes its digest); cache keys use it.
ARG FUGARO_BASE
ENV FUGARO_BASE_IMAGE=${FUGARO_BASE}
ARG REPO_URL
ARG REPO_ORIGIN=${REPO_URL}
ARG BASE_BRANCH

USER root
# Vendor tool, pinned by version and checksum (placeholder values in this fixture).
RUN curl -fsSLo /tmp/examplectl.tgz https://downloads.example.com/examplectl/1.2.3/examplectl_linux_amd64.tgz \
 && echo "0000000000000000000000000000000000000000000000000000000000000000  /tmp/examplectl.tgz" | sha256sum -c - \
 && tar -C /usr/local/bin -xzf /tmp/examplectl.tgz examplectl \
 && rm /tmp/examplectl.tgz
USER fugaro

WORKDIR /work/repo
# A push to the branch after the render step must not change what is baked
# in, so the checkout is reset to FUGARO_COMMIT, which is fetched by itself
# when it is no longer on the branch. When it can't be fetched either, the
# build fails, saying so.
ARG FUGARO_COMMIT=""
RUN --mount=type=bind,target=/src \
    --mount=type=secret,id=git-credentials,uid=1000,required=false \
    case "$FUGARO_COMMIT" in *[!0-9a-f]*) echo "FUGARO_COMMIT is not a commit ID" >&2; exit 1 ;; esac \
 && GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
      -c credential.helper='store --file=/run/secrets/git-credentials' \
      clone --quiet --branch "$BASE_BRANCH" --single-branch -- "$REPO_URL" /work/repo \
 && if [ -n "$FUGARO_COMMIT" ]; then \
      { git cat-file -e "$FUGARO_COMMIT^{commit}" 2>/dev/null \
        || GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
             -c credential.helper='store --file=/run/secrets/git-credentials' \
             fetch --quiet origin "$FUGARO_COMMIT"; } \
      && git reset --quiet --hard "$FUGARO_COMMIT" \
      || { echo "commit $FUGARO_COMMIT is no longer reachable: the branch was force-pushed; re-run the build" >&2; exit 1; }; \
    fi \
 && git remote set-url origin -- "$REPO_ORIGIN"

USER root
RUN rm -f /etc/sudoers.d/fugaro-build \
 && { [ ! -e /usr/bin/sudo ] || chmod u-s /usr/bin/sudo; } \
 && { [ ! -e /usr/bin/su ] || chmod u-s /usr/bin/su; }
USER fugaro

RUN /usr/local/lib/fugaro/finalize-checkout /work/repo

# The build time, which Cloud Build passes (empty in a local build). It is
# declared here, so a new value never invalidates the cached steps above.
ARG FUGARO_BUILT_AT=""
# What the image was built from, for the runner to report how old the image
# was at launch. built_at is left out of a local build. The checkout belongs
# to fugaro, so root is told to trust it.
USER root
RUN mkdir -p /etc/fugaro \
 && commit="$(git -c safe.directory=/work/repo -C /work/repo rev-parse HEAD)" \
 && { printf '{'; [ -z "$FUGARO_BUILT_AT" ] || printf '"built_at":"%s",' "$FUGARO_BUILT_AT"; printf '"commit":"%s"}\n' "$commit"; } > /etc/fugaro/image.json \
 && chmod 0644 /etc/fugaro/image.json
USER fugaro
